github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
theme: jekyll-theme-merlot
qfm_quirks: paragraph_end
name: Al's Place

description: Testing blog
